services:
  - type: web
    name: stellarscribe-frontend
    env: static
    buildCommand: npm install --ignore-scripts --legacy-peer-deps && npm run build
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
